name: test and deploy
on:
 push:
  branches: main
jobs:
 test:
  runs-on: ubuntu-latest
  steps:
   - name: adding code
     uses: actions/checkout@v4
   - name: Install NodeJS
     uses: actions/srtup-node@v4
     with:
      node-version: 18
   - name: Install dependencies
     run: npm ci
   - name: building code
     run:  npm test
 deploy:
  runs-on: ubuntu-latest
  steps:
   - name: adding code
     uses: actions/checkout@v4
   - name: Install NodeJS
     uses: actions/srtup-node@v4
     with:
      node-version: 18
   - name: Install dependencies
     run: npm ci
   - name: build project
     run: npm build
   - name: deploy
     run: echo "deploying"    
       